---
title: "Data Visualization - Assignment 3"
author: "Navishti Das"
date: "2/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r reading-data, include = TRUE, message=FALSE, warning=FALSE}
library(haven)
data <- read_stata("data.dta")
```

``` {r loading-library, include = TRUE, message = FALSE}
library(ggplot2)
library(dplyr)

```

```{r viz1}

data$incgrp <- (factor(data$incgrp, levels = c("Low income", "Lower middle income", "Upper middle income", "High income")))

ggplot(data = data, aes(x = year, y = mmratio,
                 group = incgrp , color = incgrp))+
  geom_line()+
  theme_classic()+
  labs(x = "Year",
       y = "Maternal Mortality ratio, per 100,000 live births",
       caption = "World Health Organization | Global Health Observatory data",
       color = "Income grouping of countries")+
  scale_color_manual(values = c("#E7B800", "#2E9FDF", "#FC4E07", "#FC9A40"))+
  ggtitle("Maternal Mortality Ratio Over Time, By Country Income Groups")+
  scale_y_continuous(breaks = seq(0,600,100))
```

```{r viz1-comment, echo=FALSE}
"This visualization shows that maternal mortality in low income countries continues to remain significantly higher than other groups, although the gap is reducing. Since 2010, maternal mortality in high and upper middle income countries has remained low and largely unchanged. Low income countries show the steepest decline in mortality over time."

```

```{r viz2}

data2 <- data %>%
  filter(year %in% c(2010, 2015))

ggplot(data2, aes(x = incgrp, y = lowbweight, 
                  fill = year))+
  geom_bar(stat = "identity",
           position = position_dodge())+
  theme_classic()+
  labs(x = "",
       y = "% new borns weighing less than 2.5 Kgs",
       caption = "World Health Organization | Global Health Observatory data",
       fill = "") +
  ggtitle("% of low birthweight babies, by country income group and years")

```

``` {r viz2-comment, echo = FALSE}
"Over the 5 year period between 2010 and 15, the incidence of low birth weight babies has barely changed for most income groups. The only noticeable change is among low income countries, similar to the pattern of changes seen in maternal mortality ratios above."
```

```{r viz3, warning=FALSE, message=FALSE}
data3 <- read_stata("data3.dta")

data3$WorldBankIncomeGroup <- (factor(data3$WorldBankIncomeGroup, levels = c("Low income", "Lower middle income", "Upper middle income", "High income")))

ggplot(data3) +
  geom_point(aes(x = log(gdppc), y = mmr, color = WorldBankIncomeGroup)) +
  geom_smooth(aes(x = log(gdppc), y = mmr), se=F) +
  theme_classic() +
  scale_x_continuous(breaks = seq(0, 14, 2)) +
  labs(x = "Log GDP per capita", y = "Maternal Mortality Ratio, per 100,000 live births",
       caption = "World Health Organization & World Bank",
       color = "Income grouping of countries") +
  ggtitle("Maternal Mortality Ratio by GDP per capita")
```

```{r viz3-comment, echo=FALSE}
"It can be expected that a country's income and MMR will be negatively correlated, such that as income increases, MMR decreases. This visualisation confirms this. While this is always true for high income countries, there are a few low and middle income countries that vary from this norm."
```

```{r viz4, message=FALSE}
data4 <- data %>%
  filter(year %in% 2015)

ggplot(data4) +
  geom_bar(aes(x = reorder(incgrp, -preganaemia), 
               y = preganaemia), 
           stat = "identity", 
           fill = '#0099FF',
           alpha = 0.5,
           width = 0.8) +
  theme_classic() +
  coord_flip()+
  labs(x = "", y = "% 15-49 year old women anaemic when pregnant",
       caption = "World Health Organization | Global Health Observatory data") +
  ggtitle("Prevalence of Anaemia in Pregnant Women")
```

